// lib/menu.ts
export const menuItems = [
  // 🌿 FASTING FOODS (150 ETB)
  {
    id: 1,
    name: "Pasta Besiga",
    price: 150,
    category: "Fasting",
    description: "Pasta mixed with special fasting sauce",
    image: "/images/pasta.jpeg",
    ingredients: "Pasta, Fasting sauce, Spices",
  },
  {
    id: 2,
    name: "Pasta Be Atikilt",
    price: 150,
    category: "Fasting",
    description: "Pasta with mixed vegetables",
    image: "/images/pasta.jpeg",
    ingredients: "Pasta, Cabbage, Carrot, Potato",
  },
  {
    id: 3,
    name: "Special Shiro",
    price: 150,
    category: "Fasting",
    description: "Our famous creamy shiro wot",
    image: "/images/shiro.jpeg",
    ingredients: "Chickpea flour, Berbere, Niter Kibbeh",
  },
  {
    id: 4,
    name: "Tegabino",
    price: 150,
    category: "Fasting",
    description: "Spicy shiro with injera pieces",
    image: "/images/shiro.jpeg",
    ingredients: "Shiro, Injera, Berbere",
  },
  {
    id: 5,
    name: "Timatim Lebleb",
    price: 150,
    category: "Fasting",
    description: "Tomato salad with chickpeas",
    image: "/images/siga.jpeg",
    ingredients: "Tomato, Chickpea, Onion, Jalapeño",
  },
  {
    id: 6,
    name: "Suf Fitfit",
    price: 150,
    category: "Fasting",
    description: "Spiced lentil fitfit",
    image: "/images/fitfit.jpeg",
    ingredients: "Lentils, Injera, Spices",
  },
  {
    id: 7,
    name: "Normal Firfir",
    price: 150,
    category: "Fasting",
    description: "Classic injera fitfit",
    image: "/images/fitfit.jpeg",
    ingredients: "Injera, Berbere sauce",
  },
  {
    id: 8,
    name: "Gomen Tibs",
    price: 150,
    category: "Fasting",
    description: "Sautéed collard greens",
    image: "/images/siga.jpeg",
    ingredients: "Collard greens, Garlic, Spices",
  },
  {
    id: 9,
    name: "Half Half (Shiro + Gomen)",
    price: 150,
    category: "Fasting",
    description: "Combination of shiro and gomen",
    image: "/images/shiro.jpeg",
    ingredients: "Shiro, Gomen",
  },
  {
    id: 10,
    name: "Half Half (Shiro + Pasta)",
    price: 150,
    category: "Fasting",
    description: "Shiro served with pasta",
    image: "/images/pasta.jpeg",
    ingredients: "Shiro, Pasta",
  },
  {
    id: 11,
    name: "Firfir Be Avocado",
    price: 150,
    category: "Fasting",
    description: "Fitfir with fresh avocado",
    image: "/images/fitfit.jpeg",
    ingredients: "Injera, Avocado, Spices",
  },
  {
    id: 12,
    name: "Ful Be Avocado",
    price: 150,
    category: "Fasting",
    description: "Fava beans with avocado",
    image: "/images/siga.jpeg",
    ingredients: "Fava beans, Avocado, Tomato",
  },

  // 🍖 NON-FASTING FOODS (200 ETB)
  {
    id: 13,
    name: "Bozena Shiro",
    price: 200,
    category: "Non-Fasting",
    description: "Shiro cooked with meat",
    image: "/images/shiro.jpeg",
    ingredients: "Shiro, Beef, Spices",
  },
  {
    id: 14,
    name: "Shiro Bekibie",
    price: 200,
    category: "Non-Fasting",
    description: "Shiro with kibbe (butter)",
    image: "/images/shiro.jpeg",
    ingredients: "Shiro, Kibbe, Spices",
  },
  {
    id: 15,
    name: "Siga Firfir",
    price: 200,
    category: "Non-Fasting",
    description: "Beef fitfir",
    image: "/images/siga.jpeg",
    ingredients: "Beef, Injera, Berbere",
  },
  {
    id: 16,
    name: "Enkulal Firfir",
    price: 200,
    category: "Non-Fasting",
    description: "Scrambled egg fitfir",
    image: "/images/egg.jpeg",
    ingredients: "Egg, Injera, Spices",
  },
  {
    id: 17,
    name: "Enkulal Be Siga",
    price: 200,
    category: "Non-Fasting",
    description: "Egg with beef",
    image: "/images/egg.jpeg",
    ingredients: "Egg, Beef, Onion",
  },
  {
    id: 18,
    name: "Pasta Be Siga",
    price: 200,
    category: "Non-Fasting",
    description: "Pasta with beef",
    image: "/images/pasta.jpeg",
    ingredients: "Pasta, Beef, Sauce",
  },
  {
    id: 19,
    name: "Pasta Be Enkulal",
    price: 200,
    category: "Non-Fasting",
    description: "Pasta with egg",
    image: "/images/pasta.jpeg",
    ingredients: "Pasta, Egg, Spices",
  },
];

export type MenuItem = typeof menuItems[0];